project:
  type: book

book:
  title: "Data Science and Society with R"
  subtitle: "DSDA/STAT 1010 - Quarto Book"
  author: "[Jason S. Byers](https://jasonsbyers.com) and [Jun Yan](https://statcomp.org)"
#  date: last-modified
  repo-url: https://github.com/statds/1010f25
  repo-actions: [issue, source]
  downloads: [pdf]
  chapters:
    - index.qmd
    - 01-computing.qmd
    - 02-git.qmd
    - 03-R.qmd
    - 04-encounter.qmd
    - 05-visual.qmd
    - 06-manipulation.qmd
    - 07-eda.qmd
    - 08-tidy.qmd
    - 09-geospat.qmd
    - 10-shiny.qmd
    - exercises.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    toc-depth: 2
    number-sections: true
    code-fold: show
    df-print: paged
    anchor-sections: true
  #  embed-resources: true
  # pdf:
  #   documentclass: scrreprt

execute:
  echo: true
  warning: false
  message: false
  freeze: auto

bibliography: references.bib
csl: apa.csl

metadata-files:
  - _course.yml
